### PR TITLE
update for comlink 3.x

### PR DESCRIPTION
**Pull request by dougmoscrop**
I did not update package.json version or anything, also `npm test` fails for me unless I `npm install --save-dev webpack` but I left that change out of this commit!

### CODE REVIEW

**Comment by dougmoscrop** [comment]
I signed the CLA

**Comment by dougmoscrop** [comment]
Looks like your CI is failing because of webpack missing too, so I've added that commit to this PR.

**Comment by dougmoscrop** [comment]
Just in case you don't get notified, sorry if you already did, @developit any chance of this getting merged?

**Comment by dougmoscrop** [comment]
Based on https://github.com/GoogleChromeLabs/comlink/issues/253 it seems this library is essentially abandoned.

**Comment by developit** [comment]
Apologies for the radio silence. I would indeed recommend going with worker-plugin + comlink. It's a little less magic and avoids the tradeoffs comlink-loader comes with.

**Pull request closed without merging**
